### ISSUE TITLE
Has the code related to CIRS integrated into this project?

### ISSUE THREAD

**Issue by jessyford** [zjunlp/EasyInstruct#17]
I just read the paper _When Do Program-of-Thought Works for Reasoning_. The result is pretty interesting and I would like to use CIRS metric to test with some other public code datasets. It is said in the paper that the code will be integrated into this project so I come to ask for help. Thank you :)

**Comment by zxlzr** [comment]
Hi, the code of CIRS has not been integrated yet, and will be added a few months later. We are still developing this porject.

**Comment by bizhen46766** [comment]
Hi~ 
Thanks for your interest in our paper  _When Do Program-of-Thought Works for Reasoning_.
We re-organize and integrate the CIRS metric into the [project](https://github.com/zjunlp/EasyInstruct/blob/9b7ba321287743cc6adf73ad2c8fbcf6f051cacd/examples/CIRS.py#L7.)

The specific usage is as follows: 
`
from easyinstruct import CodeSelector
selector = CodeSelector(
    source_dir="data/",
    source_file_path="code_example.jsonl", 
    target_dir="data/",
    manually_partion_data=True,
    min_boundary = 0.125,
    max_boundary = 0.5,
    automatically_partion_data = True,
    k_means_cluster_number = 2,
    )
selector.process()
`

 It is a preliminary version, please contact us If there are any errors or problems in the new file.
