### ISSUE TITLE
something wrong with function _get_incontext_examples() in ie_prompt.py

### ISSUE THREAD

**Issue by munian08** [zjunlp/EasyInstruct#18]
<img width="721" alt="Snipaste_2024-01-02_12-48-17" src="https://github.com/zjunlp/EasyInstruct/assets/72719408/f07b4db9-377a-4542-af8f-24efe5e157d8">
现在的写法self.examples为空，没有办法读入例子

**Comment by munian08** [comment]
框出来的这句改成for example in examples:就行

**Comment by OE-Heart** [comment]
Thanks for the heads up:) We've fixed this typo in the latest [commit](https://github.com/zjunlp/EasyInstruct/commit/2e480d3af4f715cfab795698796143d6a5d32737).
