### ISSUE TITLE
问题：1）KG2Instruct方法输出是信息抽取后的三元组如何应用？2）Evol-Instruct方法中Elimination Evolving过滤指令的代码是否可以公开？

### ISSUE THREAD

**Issue by hangchen426926** [zjunlp/EasyInstruct#20]
1、目前从代码看，KG2Instruct方法输出是信息抽取后的三元组，从三元组如何产生指令微调训练样本，能否可以详细描述，并开放相关代码？
2、Evol-Instruct方法中Elimination Evolving过滤指令原则有：
    1）与原始指令相比，进化后的指令没有提供任何信息增益；
    2）进化出的指令使得LLMs很难产生回复；
    ......
    请问这些过滤指令的原则具体是如何实现的？是否可以详细描述下，或公开相关代码？

谢谢！期盼回复~

**Comment by guihonghao** [comment]
关于问题1，KG2Instruct方法输出是信息抽取后的三元组，从三元组如何产生指令微调训练样本，你可以参考：https://github.com/zjunlp/IEPile?tab=readme-ov-file#41training-data-conversion

**Comment by hangchen426926** [comment]
> 关于问题1，KG2Instruct方法输出是信息抽取后的三元组，从三元组如何产生指令微调训练样本，你可以参考：https://github.com/zjunlp/IEPile?tab=readme-ov-file#41training-data-conversion

谢谢答复！我理解，IEPile和KG2Instruct这2种方法其实都属于信息抽取指令数据集任务，任务类型界定在信息抽取上。

**Comment by guihonghao** [comment]
KG2Instruct是通过对齐文本与知识图谱KG（远程监督）生成关系抽取数据集。IEPile是通过改造现有信息抽取数据集生成指令微调数据。可以先KG2Instruct再IEPile

**Comment by OE-Heart** [comment]
关于问题2，我们的工具中只借鉴了EvolInstruct方法中有关指令生成的部分，后续的指令筛选用的是我们自己集成的一套过滤器，你讲的这两点过滤原则可以看看官方原版的实现(https://github.com/nlpxucan/WizardLM)

**Comment by zxlzr** [comment]
请问您还有其它问题吗?

**Comment by hangchen426926** [comment]
> KG2Instruct是通过对齐文本与知识图谱KG（远程监督）生成关系抽取数据集。IEPile是通过改造现有信息抽取数据集生成指令微调数据。可以先KG2Instruct再IEPile

理解了，谢谢。
