### ISSUE TITLE
Can not generate training data via self-instruct approach.

### ISSUE THREAD

**Issue by OutdoorManofML** [zjunlp/EasyInstruct#23]
When I typed on my OpenAI API key and apply the self-instruct approach generate training data using example_seed_data.jsonl , why does it keep showing an "错误" when I click the Generate button? I would appreciate your response！

**Comment by OE-Heart** [comment]
Sorry, I'm not quite sure what's happening just from your description, could you please check and share the gradio logs?

![图片](https://github.com/user-attachments/assets/e91e40e8-568c-432a-93e8-d43667f43472)

**Comment by OE-Heart** [comment]
Hello, has your problem been solved?
