### ISSUE TITLE
problem in path in examples/kg2instruction/download_en.bash

### ISSUE THREAD

**Issue by stepankulakoff** [zjunlp/EasyInstruct#28]
line 33: wget -O model/text_classification_en.zip https://huggingface.co/datasets/ghh001/InstructIE_tool/resolve/main/text_classification_en.zip?download=true
correct:
wget -O model/text_classification_en.zip https://huggingface.co/datasets/ghh001/InstructIE_tool/resolve/main/text_classification_en.zip

no this error in Chinese version of script btw

**Comment by stepankulakoff** [comment]
yes. may be you should correct it so other people won't face with this problem
thank you for your job

**Comment by zxlzr** [comment]
We have updated the repo, thank you very much for your helpful suggestions.
