### ISSUE TITLE
缺少了这个模块

### ISSUE THREAD

**Issue by guoliangxie123** [zjunlp/EasyInstruct#3]
ModuleNotFoundError: No module named 'llama_cpp'

**Comment by zxlzr** [comment]
Sorry, there is a missing package of 'llama_cpp', we will fix it soon. I

f you do not use llama-based LLMs, you can skip the bug by  just deleting the import line. Or, you can install llama_cpp from https://github.com/ggerganov/llama.cpp.

**Comment by zxlzr** [comment]
The bug has been fixed. Please have a try.

**Comment by guoliangxie123** [comment]
thank you
