### ISSUE TITLE
ERROR: Failed building wheel for llama-cpp-python

### ISSUE THREAD

**Issue by kanswer** [zjunlp/EasyInstruct#6]
Building wheel for llama-cpp-python (pyproject.toml) ... error
  error: subprocess-exited-with-error

Not searching for unused variables given on the command line.
      -- The C compiler identification is unknown
      CMake Error at CMakeLists.txt:3 (ENABLE_LANGUAGE):
        No CMAKE_C_COMPILER could be found.

        Tell CMake where to find the compiler by setting either the environment
        variable "CC" or the CMake cache entry CMAKE_C_COMPILER to the full path to
        the compiler, or to the compiler name if it is in the PATH.

      -- Configuring incomplete, errors occurred!

ERROR: Failed building wheel for llama-cpp-python
Failed to build llama-cpp-python
ERROR: Could not build wheels for llama-cpp-python, which is required to install pyproject.toml-based projects

**Comment by wakawaka111** [comment]
You need a C compiler to compile llama-cpp-python, try update gcc to v11 if you are on linux.

**Comment by kanswer** [comment]
Finally, I download Visual Studio and corresponding C++ tools and build successfully.
