### ISSUE TITLE
ie_prompt.py中build_prompt方法有问题

### ISSUE THREAD

**Issue by Carl-Manstein** [zjunlp/EasyInstruct#7]
可能是版本更迭中有疏忽？漏了一句self.examples=examples
![E@(H_QK$6%FX@FTTR4GO_QK](https://github.com/zjunlp/EasyInstruct/assets/53854250/1bac00c3-71f4-4460-8bee-709d21223840)

**Comment by XnibyH** [comment]
Hi, I have encountered the same issue. Unfortunately, the solution above gave me another error:
![image](https://github.com/zjunlp/EasyInstruct/assets/110109114/b5d14e96-7e67-4e80-8309-5554db598a49)
or maybe it's my mistake... I cannot figure it out for now.
Could you upload the correct files?

**Comment by OE-Heart** [comment]
> 重新读了源码，发现了一些错误，出现错误的文件为easyinstruct/prompts/ie_prompt.py（在尝试用您的框架做IE） 根据ReadMe中给出的prompt方式，应当有以下修改： line82：将self.examples修改为examples ![image](https://user-images.githubusercontent.com/53854250/244401219-b2b944c7-fb65-4abd-968a-f012cf3c75e6.png) 这里应该是少样本抽取时不给examples的错误情况，由于之前没有定义self.example，这里应该去掉self line88：修改为if self.instruction and self.instruction is not None: 这是判断空值的正确写法 ![image](https://user-images.githubusercontent.com/53854250/244402144-89bea6cf-cd45-4032-a71e-0cb6c3518f07.png) line111：针对self.prompt分情况赋值的修改 ![image](https://user-images.githubusercontent.com/53854250/244402740-d6340d44-1cd7-47d2-8e62-42d3a990561a.png) ![image](https://user-images.githubusercontent.com/53854250/244402798-0affdae4-3975-4c28-a20a-a44c0bb2f5e5.png) 父类中的build_prompt方法只能在少样本的时候使用，因为不是这种情况的时候len(example)将无法正常运行 line129：if条件设错了，这个估计是不小心吧，跟其他几个ie任务的情况对比就知道了，应该是if self.domain and self.labels: ![image](https://user-images.githubusercontent.com/53854250/244404430-1274002b-208a-459c-acb9-3ed20d4330a5.png)

感谢您的指正，我们在 https://github.com/zjunlp/EasyInstruct/commit/e837cde81500b2f83ce4691ee6958dcda0107262 中进行了修复 : )

**Comment by OE-Heart** [comment]
By the way, you should Install EasyInstruct for local development to get the latest updation. We will release a new version of the package soon : )
