### ISSUE TITLE
Update Anthropic Client

### ISSUE THREAD

**Issue by krrishdholakia** [zjunlp/EasyInstruct#9]
Anthropic changed their python sdk - making this code line outdated.

https://github.com/zjunlp/EasyInstruct/blob/040f694fd1ede32255e291c2e8518dda71ee5a3c/easyinstruct/prompts/base_prompt.py#L93

Would love to know if this might help - https://github.com/BerriAI/litellm

~Simple I/O library, that standardizes all the llm api calls to the OpenAI call

```
from litellm import completion

## set ENV variables
# ENV variables can be set in .env file, too. Example in .env.example
os.environ["OPENAI_API_KEY"] = "openai key"
os.environ["ANTHROPIC_API_KEY"] = "anthropic key"

messages = [{ "content": "Hello, how are you?","role": "user"}]

# openai call
response = completion(model="gpt-3.5-turbo", messages=messages)

# anthropic call
response = completion("claude-v-2", messages)

```

**Comment by krrishdholakia** [comment]
cc: @zxlzr @OE-Heart

**Comment by OE-Heart** [comment]
Thanks for the heads up, we'll update the library soon!
